export { default as Header } from "./Header"
export { default as NavLinks } from "./NavLinks"
export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Title } from "./Title"
export { default as Skills } from "./Skills"
export { default as IconList } from "./IconList"
